---
- name: Install OpenSCAP Scanner
  win_package:
    path: https://github.com/OpenSCAP/openscap/releases/download/1.3.0/OpenSCAP-1.3.0-win32.msi
    product_id: '{6FA5F330-E7DD-47F9-9197-4C0F3B73B7FC}'
    arguments: /passive /norestart

- name: Install Visual Studio Package
  win_package:
    path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe
    product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
    arguments:
    - /install
    - /passive
    - /norestart

- name: Copy options file needed for scan
  win_copy:
    src: Windows_Server_2016_STIG.xml
    dest: C:\Program Files (x86)\OpenSCAP 1.3.0\Windows_Server_2016_STIG.xml

#will need to upgrade for Ansible 2.11
- name: create HTML report
  win_command: oscap.exe xccdf eval --profile xccdf_mil.disa.stig_profile_Mac-3_Sensitive Windows_Server_2016_STIG.xml
  args:
    chdir: C:\Program Files (x86)\OpenSCAP 1.3.0\

- name: Copy files to Tower host
  ansible.builtin.fetch:
    src: "C:\\Users\\ansible\\SCC\\Sessions\\SCAP\\All-Settings_Windows_Server_2016_STIG.html"
    dest: "/tmp/{{ inventory_hostname }}/index.html"
    flat: yes

- name: Copy folders to reports host
  ansible.builtin.copy:        
    src: "/tmp/{{ inventory_hostname }}"
    dest: "{{ file_path }}"
  delegate_to: report.shadowman.dev

- name: DISPLAY LINK TO SCAP REPORT
  ansible.builtin.debug:
    msg: "http://report.shadowman.dev/openscap/{{ inventory_hostname }}"