---
- name: Install OpenSCAP Scanner
  win_package:
    path: https://github.com/OpenSCAP/openscap/releases/download/1.3.0/OpenSCAP-1.3.0-win32.msi
    product_id: '{6FA5F330-E7DD-47F9-9197-4C0F3B73B7FC}'
    arguments: /passive /norestart

- name: Install Visual Studio Package
  win_package:
    path: https://aka.ms/vs/15/release/VC_redist.x86.exe
    product_id: none
    arguments:
    - /install
    - /passive
    - /norestart

- name: Copy options file needed for scan
  win_copy:
    src: Windows_Server_2016_STIG.xml
    dest: C:\Program Files (x86)\OpenSCAP 1.3.0\Windows_Server_2016_STIG.xml

#will need to upgrade for Ansible 2.11
- name: create HTML report
  win_command: oscap.exe xccdf eval --profile xccdf_mil.disa.stig_profile_MAC-3_Sensitive --results C:\Users\ansible\report.xml --report C:\Users\ansible\index.html Windows_Server_2016_STIG.xml
  args:
    chdir: C:\Program Files (x86)\OpenSCAP 1.3.0\
  register: command_result
  failed_when: command_result.rc != 2

- name: Copy files to Tower host
  ansible.builtin.fetch:
    src: "C:\\Users\\ansible\\{{ item }}"
    dest: "/tmp/{{ inventory_hostname }}/"
    flat: yes
  loop:
    - index.html
    - report.xml

- name: Copy folders to reports host
  ansible.builtin.copy:        
    src: "/tmp/{{ inventory_hostname }}"
    dest: "{{ file_path }}"
  delegate_to: report.shadowman.dev

- name: DISPLAY LINK TO SCAP REPORT
  ansible.builtin.debug:
    msg: "http://report.shadowman.dev/openscap/{{ inventory_hostname }}"