collections:
  - name: redhat.insights

  - name: chocolatey.chocolatey

  - name: community.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: ansible.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: ansible.posix

  - name: shadowman.reports
    source: https://towerhub.shadowman.dev/api/galaxy/content/published/


  