collections:
  - name: redhat.insights

  - name: chocolatey.chocolatey

  - name: community.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: ansible.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: ansible.posix

  - name: ansible.netcommon

  - name: google.cloud

  - name: community.kubernetes
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: community.general
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/


  