---
- name: Gather Facts
  hosts: tag_Insights

  vars:
    scan_use_checksum: false
    scan_use_recursive: false

  tasks:

    - name: Scan packages (Unix/Linux)
      shadowman.reports.scan_packages:
        os_family: '{{ ansible_os_family }}'
      when: ansible_os_family != "Windows"

    - name: Scan services (Unix/Linux)
      shadowman.reports.scan_services:
      when: ansible_os_family != "Windows"

- name: Build report with facts
  hosts: report.shadowman.dev
  gather_facts: no
  tasks:

    - name: build a report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_linux