---
- name: Create Linux Report
  hosts: all
  tasks:

    - name: Scan Systems for detailed report
      ansible.builtin.include_role:
        name: shadowman_scan_systems
      when: detailedreport == 'True'

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_linux
        apply:
          delegate_to: rhel8.shadowman.dev
          run_once: true
