---

- name: Add to DNS
  ipa_host:
    name: "{{ fqdn }}"
    ip_address: "{{ ansible_host }}"
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: present
    force: yes
  delegate_to: localhost
  no_log: true
  become: no