- name: Playbook to configure IPA clients
  hosts: "{{ vm_name | default('all')}}"

  tasks:

  - name: Install IPA Client for RHEL 7
    ansible.builtin.yum:
      name: ipa-client
      state: present
    when: ansible_distribution_version is match("7.*")

  - name: Install IPA Client for RHEL 8
    ansible.builtin.dnf:
      name: ipa-client
      state: present
    when: ansible_distribution_version is match("8.*")

  - name: run ipa client script
    ansible.builtin.command: "ipa-client-install --principal '{{IPA_USER}}' --password '{{ IPA_PASS }}' --hostname '{{ fqdn }}' --enable-dns-updates --mkhomedir --unattended"
    register: output
    failed_when: output.rc == 2

