---
- name: Set timezone
  community.windows.win_timezone:
    timezone: Eastern Standard Time

- name: Add to DNS
  community.general.ipa_host:
    name: "{{ fqdn }}"
    ipaddress: "{{ ansible_host }}"
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: present
    force: yes
  delegate_to: localhost
  become: false