- name: Playbook to configure IPA clients
  hosts: "{{ vm_name | default('all')}}"

  tasks:

  - name: Install IPA Client for RHEL 7
    yum:
      name: ipa-client
      state: present
    when: ansible_distribution_version is match("7.*")

  - name: Install IPA Client for RHEL 8
    dnf:
      name: ipa-client
      state: present
    when: ansible_distribution_version is match("8.*")

  - name: Add to DNS
    ipa_host:
      name: "{{ fqdn }}"
      ip_address: "{{ ansible_host }}"
      ipa_pass: "{{ IPA_PASS }}"
      ipa_host: "{{ IPA_HOST }}"
      ipa_user: "{{ IPA_USER }}"
      state: present
      force: yes
    delegate_to: localhost
    no_log: true
    become: no

  - name: run ipa client script
    command: "ipa-client-install --principal '{{IPA_USER}}' --password '{{ IPA_PASS }}' --domain 'shadowman.dev' --server '{{IPA_HOST }}' --hostname '{{ fqdn }}' --enable-dns-updates --mkhomedir --unattended"
    register: output
    failed_when: output.rc == 2

