---
- name: copy SSH key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: https://github.com/lynndixon.keys

- name: Install Katello RPM for Satellite Server for RHEL 7
  ansible.builtin.yum:
    name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  when: ansible_distribution_version is match("7.*")

- name: Install Katello RPM for Satellite Server for RHEL 8
  ansible.builtin.dnf:
    name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  when: ansible_distribution_version is match("8.*")

- name: Use Activation Key to Register RHEL7 Machine to Satellite
  community.general.redhat_subscription:
    state: present
    activationkey: "RHEL7 Everything"
    org_id: Shadow_Man
  when: ansible_distribution_version is match("7.*")

- name: Use Activation Key to Register RHEL8 Machine to Satellite
  community.general.redhat_subscription:
    state: present
    activationkey: "RHEL8"
    org_id: Shadow_Man
  when: ansible_distribution_version is match("8.*")

- name: Enable Repositories for RHEL 7
  community.general.rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
    purge: True
  when: ansible_distribution_version is match("7.*")

- name: Enable Repositories for RHEL 8
  community.general.rhsm_repository:
    name:
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-baseos-rpms
    purge: True
  when: ansible_distribution_version is match("8.*")

- name: Add Fancy Legal Disclaimer (MOTD)
  ansible.builtin.copy:
    src: templates/add_motd
    dest: /etc/motd

- name: Install dnf utils RHEL 8
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  when: ansible_distribution_version is match("8.*")

- name: Install IPA Client for RHEL 7
  ansible.builtin.yum:
    name: ipa-client
    state: present
  when: ansible_distribution_version is match("7.*")

- name: Install IPA Client for RHEL 8
  ansible.builtin.dnf:
    name: ipa-client
    state: present
  when: ansible_distribution_version is match("8.*")

- name: Run IPA Client Script to add to IDM
  ansible.builtin.command: "ipa-client-install --principal '{{IPA_USER}}' --password '{{ IPA_PASS }}' --hostname '{{ fqdn }}' --enable-dns-updates --mkhomedir --unattended"
  register: output
  failed_when: output.rc == 2 or output.rc >= 4
  changed_when: output.rc == 0