---

- name: Add Windows host to AD
  win_domain_membership:
    dns_domain_name: ad.shadowman.dev
    hostname: "{{ fqdn.split('.')[0] }}"
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpassword }}" 
    domain_ou_path: "OU=Windows,OU=Servers,DC=ad,DC=shadowman" 
    state: domain
  register: domain_state

- name: Reboot server if needed
  ansible.windows.win_reboot:
  when: domain_state.reboot_required