---
- name: Update firewall ports
  hosts: all
  gather_facts: false
   
  collections:
    - ansible.posix

  tasks:  
  - name: Open Firewalld for apache
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled 
    notify: restart_firewalld

  - name: Open Firewalld for SSL
    ansible.posix.firewalld:
      service: https
      permanent: yes
      state: enabled
    notify: restart_firewalld

  - name: Block all other ICMP
    ansible.posix.firewalld:
      zone: drop
      state: enabled
      permanent: yes
    notify: restart_firewalld

    
  handlers:
    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted