---
- name: Block IP on firewall 
  hosts: all
  gather_facts: false
   
  collections:
    - ansible.posix

  tasks:  

  - name: Block all ICMP from source address
    ansible.posix.firewalld:
      zone: drop
      state: enabled
      permanent: yes
      source: 192.168.200.3/24
    notify: restart_firewalld

    
  handlers:
    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted