---
- name: Perform hostname Set
  hosts: "{{ vm_name | default('all')}}"
  gather_facts: true

  vars:
    - vm_names: "{{ vm_name.split(',') }}"
    
  tasks:

  - name: RHEL Hostname Set
    hostname:
      name: "{{ inventory_hostname }}"
    when: ansible_os_family is match("RedHat")

  - name: Restart qemu agent
    service:
      name: qemu-guest-agent
      state: restarted