---
- name: Test IP
  hosts: all
  gather_facts: false

  tasks:

    - name: get IP
      ansible.builtin.uri:
        url: http://{{ ansible_host }}/index.html
        validate_certs: no
        return_content: yes
      delegate_to: localhost