---
- name: Leapp Upgrade
  hosts: all
  gather_facts: false

  tasks:

    - name: Enable Extra Repository for RHEL 7
      rhsm_repository:
        name: rhel-7-server-extras-rpms
        state: enabled

    - name: Unset RHSM release
      rhsm_release:
          release: null
    
    - name: Clear yum versionlock
      command: "yum versionlock clear"
      ignore_errors: true

    - name: Install Leapp
      yum:
        name: 
          - leapp
          - leapp-repository
        state: latest

    - name: Download and Unarchive
      unarchive:
        src: https://access.redhat.com/node/3664871/5121/0/19333901/leapp-data13.tar.gz
        dest: /etc/leapp/files
        mode: 0440
        remote_src: yes

    - name: Run pre-upgrade
      command: "leapp preupgrade"