---
- name: Leapp Run Upgrade
  hosts: all
  gather_facts: false

  tasks:

    - name: Run upgrade
      command: "leapp upgrade"
    
    - name: Reboot Server
      reboot:

    - name: Run Setup to verify upgrade
      setup: