---
- name: Line in file test
  hosts: all
  connection: local
  vars:
    ip_address: 10.1.1.1
    api_key: aaaaaa

  tasks:
    - name: insert conf
      template:
        src: templates/test.conf.j2
        dest: "/home/network/test.conf" 