---
- name: Patch RHEL Servers
  hosts: all
  gather_facts: false

  tasks:

    - name: upgrade all packages (dnf)
      become: yes
      become_method: su
      dnf:
        name: '*'
        state: latest
      delegate_to: localhost
      run_once: true