---
- name: Patch RHEL Servers
  hosts: all

  tasks:

      block: 
        - name: Patching role
          include_role:
            name: shadowman_patching

      rescue:
        - name: Patching role
          include_role:
            name: shadowman_snapshot_restore_rhv