---
- name: Patch RHEL Servers
  hosts: all
  gather_facts: false

  tasks:

    - name: check list
      ansible.builtin.yum:
        list: updates
      register: result
      until:  result.results == ""
      retries: 60
      delay: 5

