---
- name: Patch RHEL Servers
  hosts: all
  gather_facts: false

  tasks:

    - name: upgrade all packages (dnf)
      become: yes
      dnf:
        name: '*'
        state: latest
      connection: local
      run_once: true