---
- name: Patch RHEL Servers
  hosts: all

  tasks:
    - name: upgrade all packages (yum)
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: "{{ exclude_packages }}"
      when: ansible_pkg_mgr == "yum"

    - name: upgrade all packages (dnf)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: "{{ exclude_packages }}"
      when: ansible_pkg_mgr == "dnf"