---
- name: Patch RHEL Servers
  hosts: all
  vars:
    exclude_packages: "{{ exclude.split(',') }}"

  tasks:
    - name: upgrade all packages (yum)
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: "{{ exclude_packages }}"
      when: ansible_pkg_mgr == "yum"

    - name: upgrade all packages (dnf)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: "{{ exclude_packages }}"
      when: ansible_pkg_mgr == "dnf"

    - name: Check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      register: result
      changed_when: result.rc == 1
      failed_when: result.rc > 1
      check_mode: no

    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
      when: result.rc == 1