---
- name: Patch RHEL Servers
  hosts: all
  gather_facts: false

  tasks:

    - name: Patch Server
      ansible.builtin.yum:
        name: '*'
        state: latest
      async: 1000
      poll: 0
      register: yum_sleeper

    - name: Check on Patch Status {{ inventory_hostname }}
      async_status:
        jid: "{{ yum_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10


