---
- name: Patch RHEL Servers
  hosts: localhost

  tasks:
    - name: upgrade all packages (yum)
      yum:
        name: '*'
        state: latest
        exclude: "{{ exclude_packages }}"
      when: ansible_pkg_mgr == "yum"

    - name: upgrade all packages (dnf)
      dnf:
        name: '*'
        state: latest
        exclude: "{{ exclude_packages }}"
      when: ansible_pkg_mgr == "dnf"