---
- name: Patch RHEL Servers
  hosts: all
  
  roles:
    - shadowman_patching

- name: Build patching report
  hosts: report.shadowman.dev
  tasks:

    - name: build a report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_linux_patch
