---
- name: Patch RHEL Servers
  hosts: all
  gather_facts: false

  tasks:

    - name: Check Remaining Packages {{ inventory_hostname }}
      ansible.builtin.yum:
        list: updates
      register: result
      until:  result.results == []
      retries: 2
      delay: 5

