---
- name: Patch RHEL Servers
  hosts: all
  gather_facts: false

  tasks:

    - name: Patch Server
      ansible.builtin.yum:
        name: '*'
        state: latest
      async: 1000
      poll: 0
      register: yum_sleeper

    - name: Check Remaining Packages {{ inventory_hostname }}
      ansible.builtin.yum:
        list: updates
      register: result
      until:  result.results == []
      retries: 50
      delay: 5

    - name: Clear Async Job Status
      async_status:
        jid: "{{ yum_sleeper.ansible_job_id }}"
        mode: cleanup
      

