---
- name: Setup RHEL for Template
  hosts: "{{ operating_system }}_updates.shadowman.dev"

  roles:
    - shadowman_rhel_register
    - shadowman_add_to_idm
    - shadowman_patching
    - shadowman_rhel_template_seal





