---
- name: Setup RHEL for Template
  hosts: all

  tasks:

    - name: Install Katello RPM for Satellite Server for RHEL 7
      yum:
        name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
        state: present
      when: ansible_distribution_version is match("7.*")

    - name: Install Katello RPM for Satellite Server for RHEL 8
      dnf:
        name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
        state: present
      when: ansible_distribution_version is match("8.*")

    - name: Use Activation Key to Register RHEL7 Machine to Satellite
      redhat_subscription:
        state: present
        activationkey: "RHEL7 Everything"
        org_id: Shadow_Man
      when: ansible_distribution_version is match("7.*")

    - name: Use Activation Key to Register RHEL8 Machine to Satellite
      redhat_subscription:
        state: present
        activationkey: "RHEL8"
        org_id: Shadow_Man
      when: ansible_distribution_version is match("8.*")

    - name: Enable Repositories for RHEL 7
      rhsm_repository:
        name:
          - rhel-7-server-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-optional-rpms
        purge: True
      when: ansible_distribution_version is match("7.*")

    - name: Enable Repositories for RHEL 8
      rhsm_repository:
        name:
          - rhel-8-for-x86_64-appstream-rpms
          - rhel-8-for-x86_64-baseos-rpms
        purge: True
      when: ansible_distribution_version is match("8.*")

    - name: upgrade all packages (yum)
      yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: upgrade all packages (dnf)
      dnf:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == "dnf"

    - name: Enable initial-setup service
      systemd:
        name: initial-setup.service
        enabled: yes

    - name: Set Machine ID file permissions
      file:
        path: /etc/machine-id
        mode: 0777

    - name: Unregister this machine from Satellite
      redhat_subscription:
        state: absent
        org_id: Shadow_Man

    - name: Remove and Clean all Subscription Data
      shell: subscription-manager remove --all && subscription-manager clean

    - name: Delete All Machine Specific Files
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /var/lib/dbus/machine-id
        - /etc/rhsm/facts/katello.facts
        - /etc/ssh/ssh_host_*
        - /etc/udev/rules.d/70-persistent-*






