---
- name: Set stat
  hosts: all

  tasks:

    - name: Set stats test
      ansible.builtin.set_stats:
        data:
          uptime: "{{ ansible_facts.ansible_uptime_seconds }}"
        per_host: yes
    