- name: Update/Create/Remove IDM group
  hosts: localhost
  gather_facts: false
  vars:
    - users: "{{ survey_users.split('\n') }}"
  tasks: 
    - name: Update/Create/Remove IDM group
      ipa_group:
        name: "{{ group_name }}"  
        state: "{{ state }}"
        user: "{{ users|default(omit) }}"
        ipa_pass: "{{ IPA_PASS }}"
        ipa_host: "{{ IPA_HOST }}"
        ipa_user: "{{ IPA_USER }}"
   
