- name: Update user password
  hosts: all
  gather_facts: false
  tasks: 
    - name: Change User password
      ansible.windows.win_user:
        name: "{{ user_name }}"  
        password: "{{ password }}"
      no_log: true
   
