- name: Create/Update User in AD
  hosts: all
  gather_facts: false
  tasks: 
    - name: Create/Update User in AD
      win_user:
        firstname: "{{ first_name }}"  
        surname: "{{ last_name }}"
        name: "{{ username }}"
        password: "{{ password }}"
        state: present
        update_password: on_create
        domain_username: "{{ domainuser }}"
        domain_password: "{{ domainpassword }}" 
   
