- name: Update/Create/Remove IDM user
  hosts: localhost
  gather_facts: false
  tasks: 
    - name: Update/Create/Remove IDM user
      ipa_user:
        name: "{{ user_name }}"  
        state: "{{ state }}"
        givenname: "{{ first_name }}"
        sn: "{{ last_name }}"
        password: "{{ password }}"
        ipa_pass: "{{ IPA_PASS }}"
        ipa_host: "{{ IPA_HOST }}"
        ipa_user: "{{ IPA_USER }}"
      no_log: true
   
