---
- name: Windows patching playbook
  hosts: all
  gather_facts: false

  collections:
    - ansible.windows
    
  tasks:

  - name: Check for packages to include
    set_fact:
      whitelist_packages: "{{ whitelist.split(',') }}"
    when: whitelist != ''

  - name: Check for packages to exclude
    set_fact:
      blacklist_packages: "{{ blacklist.split(',') }}"
    when: blacklist != ''

  - name: Install Windows Updates
    ansible.windows.win_updates:
      category_names: "{{ categories | default(omit) }}"
      reboot: '{{ reboot_server | default(yes) }}'
      whitelist: "{{ whitelist_packages | default(omit) }}"
      blacklist: "{{ blacklist_packages | default(omit) }}"
    register: patchresult

  - name: Display Patching Results
    debug:
      msg: "{{ patchresult | json_query('updates.*.title') }}"