---
- name: Windows patching playbook
  hosts: tag_Windows

  collections:
    - ansible.windows
    
  tasks:

  - name: Check for packages to include
    set_fact:
      whitelist_packages: "{{ whitelist.split(',') }}"
    when: whitelist != ''

  - name: Check for packages to exclude
    set_fact:
      blacklist_packages: "{{ blacklist.split(',') }}"
    when: blacklist != ''

  - name: Install Windows Updates
    ansible.windows.win_updates:
      category_names: "{{ categories | default(omit) }}"
      reboot: '{{ reboot_server | default(yes) }}'
      whitelist: "{{ whitelist_packages | default(omit) }}"
      blacklist: "{{ blacklist_packages | default(omit) }}"
    register: patchresult
    
  - name: Display Patching Results
    debug:
      msg: "{{ patchresult | json_query('updates.*.title') }}"

  - name: Set patching data for ServiceNow
    set_stats:
      data:
        work_notes: "[code]<h3>{{ inventory_hostname }}</h3>[/code] {{ patchresult | json_query('updates.*.title') | to_nice_json }}"
        expose_to_cloud_redhat_com_results: "{{ inventory_hostname }}:{{ patchresult | json_query('updates.*.title') | to_nice_json }}"
    when: 
      - patchresult.found_update_count | int > 0
      - ticket_number is defined

  - name: Set patching data for ServiceNow
    set_stats:
      data:
        work_notes: "[code]<h3>{{ inventory_hostname }}</h3>[/code] Compliant"
        expose_to_cloud_redhat_com_results: "{{ inventory_hostname }}: Compliant"
    when: 
      - patchresult.found_update_count | int <= 0
      - ticket_number is defined

- name: Build patching report
  hosts: report.shadowman.dev
  tasks:

    - name: build a report
      include_role:
        name: shadowman.reports.build_report_windows_patch