---
- name: Ensure python simlink exists
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
    owner: root
    group: root
    mode: 0755
  when: ansible_python_version != "2.7.5"

- name: Scan packages (Unix/Linux)
  shadowman.reports.scan_packages:
    os_family: '{{ ansible_os_family }}'
  when: ansible_os_family != "Windows"

- name: Scan services (Unix/Linux)
  shadowman.reports.scan_services:
  when: ansible_os_family != "Windows"
