---
- name: Scan packages (Unix/Linux)
  scan_packages:
    os_family: '{{ ansible_os_family }}'
  when: ansible_os_family != "Windows"

- name: Scan services (Unix/Linux)
  shadowman.reports.scan_services:
  when: ansible_os_family != "Windows"