---
- name: copy SSH key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: https://github.com/lynndixon.keys

- name: Add Fancy Legal Disclaimer (MOTD)
  ansible.builtin.copy:
    src: templates/add_motd
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
