---
- name: Install SCAP Scanner
  chocolatey.chocolatey.win_chocolatey:
    name: scap-compliance-checker
    state: latest

#will need to upgrade for Ansible 2.11
- name: create HTML report
  win_command: cscc.exe -o options.xml
  args:
    chdir: C:\Program Files\SCAP Compliance Checker 5.4.2\

- name: Copy files to Tower host
  ansible.builtin.fetch:
    src: "C:\\Users\\Administrator\\SCC\\Sessions\\SCAP\\{{ inventory_hostname | split('.')[0] | upper }}_All-Settings_Windows_Server_2016_STIG-002.001.html"
    dest: "/tmp/{{ inventory_hostname }}/index.html"
    flat: yes

- name: Copy folders to reports host
  ansible.builtin.copy:        
    src: "/tmp/{{ inventory_hostname }}"
    dest: "{{ file_path }}"
  delegate_to: report.shadowman.dev

- name: DISPLAY LINK TO INVENTORY REPORT
  ansible.builtin.debug:
    msg: "http://report.shadowman.dev/openscap/{{ inventory_hostname }}"