---
- name: ensure excluded config is fetched
  ansible.builtin.fetch:
    src: /etc/yum.conf.backup
    dest: /tmp/yum.conf.backup
    flat: yes
  check_mode: false
  delegate_to: tower1.shadowman.dev
  run_once: true

- name: ensure excluded config is copied
  ansible.builtin.copy:
    src: /tmp/yum.conf.backup
    dest: /etc/yum.conf
    owner: root
    group: root
    mode: '0644'

- name: upgrade all packages (dnf)
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Check to see if we need a reboot
  ansible.builtin.command: needs-restarting -r
  register: result
  changed_when: result.rc == 1
  failed_when: result.rc > 1
  check_mode: false

- name: Reboot Server if Necessary
  ansible.builtin.reboot:
  when: result.rc == 1

- name: ensure clean config is fetched
  ansible.builtin.fetch:
    src: /etc/yum.conf.cleanbackup
    dest: /tmp/yum.conf.cleanbackup
    flat: yes
  check_mode: false
  delegate_to: tower1.shadowman.dev
  run_once: true

- name: restore regular config for AAP updates
  ansible.builtin.copy:
    src: /tmp/yum.conf.cleanbackup
    dest: /etc/yum.conf
    owner: root
    group: root
    mode: '0644'
